##################################################################
# A Github action used to check pull requests on CLI Client
# More info at https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
##################################################################

name: Check pull request on CLI Client
on:
  push:
    branches: [main]
    paths:
      - "apps/cli/**"
      - ".github/workflows/check-pull-request-cli-client.yaml"
  pull_request:
    branches: [main]
    paths:
      - "apps/cli/**"
      - ".github/workflows/check-pull-request-cli-client.yaml"

jobs:
  build:
    name: Build CLI Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache-dependency-path: apps/cli/go.sum

      - name: Build
        working-directory: ./apps/cli
        run: go build ./...

  lint:
    name: Lint CLI Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache-dependency-path: apps/cli/go.sum

      - name: Run golangci-lint
        working-directory: ./apps/cli
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run --timeout=30m ./...

  run-tests:
    name: Run tests in CLI Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache-dependency-path: apps/cli/go.sum

      - name: Run tests
        working-directory: ./apps/cli
        run: go test -v -race ./...
